// Store configuration. For live catalogue updates, connect the Google Apps Script endpoint described in SETUP.md.
const CONFIG={whatsapp:"9390662074",instagram:"https://www.instagram.com/urs_highstreet?utm_source=ig_web_button_share_sheet&stkn=ZDNlZDc0MzIxNw==",apiUrl:""};
const FITS=["Regular Fit","Oversized Fit","Sweatshirt","Hoodie"],SIZES=["XS","S","M","L","XL","XXL"];
const starter=[
{id:"HS001",name:"HIGHSTREET ORIGINALS",art:"HIGH<br>STREET",category:"Graphic",price:699,types:["Regular Fit","Oversized Fit"],sizes:SIZES,season:"Core",active:true,image:"",badge:"FIRST DROP"},
{id:"HS002",name:"STAY WEIRD",art:"STAY<br>WEIRD",category:"Graphic",price:749,types:["Oversized Fit","Hoodie"],sizes:SIZES,season:"Seasonal",active:true,image:"",badge:"NEW"},
{id:"HS003",name:"LESS TALK",art:"LESS<br>TALK",category:"Minimal",price:649,types:["Regular Fit","Sweatshirt"],sizes:SIZES,season:"Core",active:true,image:"",badge:"ESSENTIAL"},
{id:"HS004",name:"Mee Innocent friend kosam..",art:"YOUR ART",category:"Graphic",price:399,types:["Regular Fit","Oversized Fit"],sizes:SIZES,season:"Core",active:true,image:"images/Innocent%20X%20Graphic%20Tee%20Front%20and%20Back.png",badge:"NEW"}
];
let products=load("hs_products",starter),events=load("hs_events",[{id:"EV1",title:"THE FIRST DROP",details:"Explore the opening HIGHSTREET collection.",badge:"NOW LIVE",active:true},{id:"EV2",title:"CUSTOM DESIGN WEEK",details:"Bring your idea. Let's make it wearable.",badge:"CUSTOM",active:true}]),cart=[],activeFit="All",activeCat="All",admin=false;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}function save(){localStorage.setItem("hs_products",JSON.stringify(products));localStorage.setItem("hs_events",JSON.stringify(events))}
function wa(msg){if(!/^\\d{10,15}$/.test(CONFIG.whatsapp)){alert("Set your WhatsApp number in app.js or Admin → Settings first.");return null}return "https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent(msg)}
function renderEvents(){document.getElementById("events").innerHTML=events.filter(e=>e.active).map(e=>`<article class="event">${e.image?`<img src="${esc(e.image)}" alt="">`:''}<small>${esc(e.badge||"HIGHSTREET")}</small><b>${esc(e.title)}</b><span>${esc(e.details)}</span></article>`).join("")||"<p>No events right now. Check back soon.</p>"}
function renderFilters(){document.getElementById("categoryFilters").innerHTML=["All","Graphic","Minimal"].map(x=>`<button data-cat="${x}" class="${activeCat===x?'active':''}">${x.toUpperCase()}</button>`).join("");document.getElementById("fitFilters").innerHTML=["All",...FITS].map(x=>`<button data-fit="${x}" class="${activeFit===x?'active':''}">${x.toUpperCase()}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;render()});document.querySelectorAll("[data-fit]").forEach(b=>b.onclick=()=>{activeFit=b.dataset.fit;render()})}
function render(){renderFilters();let shown=products.filter(p=>p.active&&(activeCat==="All"||p.category===activeCat)&&(activeFit==="All"||p.types.includes(activeFit)));document.getElementById("products").innerHTML=shown.map(p=>`<article><div class="product-img">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:`<div class="shirt-fallback">${p.art||esc(p.name)}</div>`}<span class="pill">${esc(p.badge||p.season)}</span></div><div class="pinfo"><div><h3>${esc(p.name)}</h3><p>${p.types.map(esc).join(" · ")}</p></div><span class="price">₹${p.price}</span></div><div class="orderline"><select id="size-${p.id}">${p.sizes.map(s=>`<option>${esc(s)}</option>`).join("")}</select><button data-add="${p.id}">ADD TO BAG +</button></div></article>`).join("")||"<p>No products in this filter yet.</p>";document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{let p=products.find(x=>x.id===b.dataset.add),size=document.getElementById("size-"+p.id).value;cart.push({id:p.id,name:p.name,size,price:Number(p.price)});renderCart()})}
function renderCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartItems").innerHTML=cart.map((x,i)=>`<div class="cart-row"><span><b>${esc(x.name)}</b><br>${esc(x.size)} · ₹${x.price}</span><button data-remove="${i}">REMOVE</button></div>`).join("")||"<p>Your bag is empty.</p>";document.getElementById("cartTotal").textContent="₹"+cart.reduce((a,x)=>a+x.price,0);document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function openDrawer(){document.getElementById("cartDrawer").classList.add("open");document.getElementById("scrim").classList.add("show")}function closeAll(){document.getElementById("cartDrawer").classList.remove("open");document.getElementById("scrim").classList.remove("show")}
document.getElementById("cartOpen").onclick=openDrawer;document.getElementById("scrim").onclick=closeAll;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.close).classList.remove("show");closeAll()});
document.getElementById("checkout").onclick=()=>{if(!cart.length)return alert("Your bag is empty.");let lines=cart.map(x=>`${x.name} / ${x.size} / ₹${x.price}`).join("\n");let total=cart.reduce((a,x)=>a+x.price,0),url=wa(`Hi HIGHSTREET! I'd like to place this order:\n${lines}\nTotal: ₹${total}\nPlease confirm availability, delivery charges and payment details.`);if(url)window.open(url,"_blank")};
document.getElementById("customForm").onsubmit=e=>{e.preventDefault();let d=new FormData(e.target),u=wa(`Hi HIGHSTREET! Custom order request\nName: ${d.get("name")}\nIdea: ${d.get("idea")}\nFit: ${d.get("fit")}`);if(u)window.open(u,"_blank")};
document.getElementById("igLink").href=CONFIG.instagram;document.getElementById("year").textContent=new Date().getFullYear();
const modal=document.getElementById("adminModal");document.getElementById("adminOpen").onclick=()=>modal.classList.add("show");
document.getElementById("previewLogin").onclick=()=>{admin=true;document.getElementById("adminLogin").hidden=true;document.getElementById("adminPanel").hidden=false;renderAdmin()};
document.getElementById("adminLogout").onclick=()=>{admin=false;document.getElementById("adminLogin").hidden=false;document.getElementById("adminPanel").hidden=true;modal.classList.remove("show")};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabpane").forEach(x=>x.hidden=true);document.getElementById(b.dataset.tab).hidden=false;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("selected",x===b))});
function renderAdmin(){document.getElementById("adminProductList").innerHTML=products.map(p=>`<div class="admin-item"><span>${esc(p.name)} · ${p.types.join(", ")}</span><span><button data-edit="${p.id}">EDIT</button> <button data-del="${p.id}">DELETE</button></span></div>`).join("");document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{products=products.filter(p=>p.id!==b.dataset.del);save();render();renderAdmin()});document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>fillProduct(products.find(p=>p.id===b.dataset.edit)));document.getElementById("adminEventList").innerHTML=events.map(e=>`<div class="admin-item"><span>${esc(e.title)}</span><button data-edel="${e.id}">DELETE</button></div>`).join("");document.querySelectorAll("[data-edel]").forEach(b=>b.onclick=()=>{events=events.filter(e=>e.id!==b.dataset.edel);save();renderEvents();renderAdmin()})}
function fillProduct(p){let f=document.getElementById("productForm");for(let k of ["id","name","image","art","price","category","season"])f.elements[k].value=p[k]??"";f.querySelectorAll('[name="types"]').forEach(x=>x.checked=p.types.includes(x.value));f.querySelectorAll('[name="sizes"]').forEach(x=>x.checked=p.sizes.includes(x.value));f.elements.active.checked=p.active;document.getElementById("productsTab").scrollIntoView({behavior:"smooth"})}
document.getElementById("productForm").onsubmit=e=>{e.preventDefault();let f=e.target,d=new FormData(f),id=d.get("id")||"HS"+Date.now(),old=products.find(p=>p.id===id);let p={id,name:d.get("name"),image:d.get("image"),art:d.get("art"),price:+d.get("price"),category:d.get("category")||"Graphic",types:[...f.querySelectorAll('[name="types"]:checked')].map(x=>x.value),sizes:[...f.querySelectorAll('[name="sizes"]:checked')].map(x=>x.value),season:d.get("season"),active:f.elements.active.checked,badge:old?.badge||"NEW"};if(!p.types.length||!p.sizes.length)return alert("Select at least one product type and size.");if(old)products=products.map(x=>x.id===id?p:x);else products.unshift(p);save();f.reset();f.elements.id.value="";render();renderAdmin()};
document.getElementById("eventForm").onsubmit=e=>{e.preventDefault();let d=new FormData(e.target);events.unshift({id:"EV"+Date.now(),title:d.get("title"),details:d.get("details"),image:d.get("image"),badge:d.get("badge"),active:e.target.elements.active.checked});save();renderEvents();renderAdmin();e.target.reset()};
document.getElementById("settingsForm").onsubmit=e=>{e.preventDefault();let d=new FormData(e.target);CONFIG.whatsapp=d.get("whatsapp").replace(/\D/g,"");CONFIG.instagram=d.get("instagram");document.getElementById("igLink").href=CONFIG.instagram;alert("Saved for this page session. For permanent live settings, update CONFIG in app.js or connect the backend.");};
render();renderEvents();renderCart();
